apiVersion: v2
publisher: ms-python
name: ibm-serverconnection
version: latest
type: VS Code extension
displayName: Jupyter server
title: Jupyter server
description: custom jupyter server connection
icon: /v3/images/ms-python-python-icon.png
repository: https://github.com/Microsoft/vscode-python
category: Language
firstPublicationDate: '2020-04-27'
spec:
  extensions:
    - 'https://raw.githubusercontent.com/avulavasudha/vsixfiles/master/jupyterserver-0.0.9.vsix'
