apiVersion: v2
publisher: ms-python
name: vscode-didact-python
version: 2020.4.76186
type: VS Code extension
displayName: vscode-didact-python
title: vscode python didact
description: activate python on workspace start
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/Microsoft/vscode-python
category: Language
firstPublicationDate: '2020-04-27'
spec:
  extensions:
  - https://raw.githubusercontent.com/avulavasudha/vsixfiles/master/ms-toolsai.jupyter-2021.2.576440691.vsix
